[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.9.1",
    "fastapi>=0.122.0",
    "langchain>=1.1.0",
    "langchain-ollama>=1.0.0",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
